### PR TITLE
Refactor `livesplit.rs` and fix warnings

### LINKED ISSUE #407: Refactor `livesplit.rs` code

### PR DESCRIPTION
**Pull request by LukeSaward1**
Resolves #407

### CODE REVIEW

File: rtil/src/threads/ue/rebo/livesplit.rs [hunk 1]
```diff
@@ -233,25 +274,23 @@ impl Run {
             };
             run.metadata_mut().set_speedrun_com_variable("New Game Glitch", cat);
         }
-        state.timer.set_run(run).unwrap();
+        self.timer.set_run(run.clone()).expect("The provided `Run` contains no segments");
```
Comment (oberien) [inline rtil/src/threads/ue/rebo/livesplit.rs:277]: unnecessary `clone`

File: rtil/src/threads/ue/rebo/livesplit.rs [hunk 2]
```diff
@@ -283,9 +322,8 @@ impl Run {
             .map_err(|e| SplitsLoadError::OpenFailed(path_display.to_owned(), e.to_string()))?;
         let parsed_run = composite::parse(&file, None)
             .map_err(|e| SplitsLoadError::ParseFailed(path_display.to_owned(), e.to_string()))?;
-        let mut state = LIVESPLIT_STATE.lock().unwrap();
-        state.timer.reset(true);
-        state.timer.set_run(parsed_run.run).unwrap();
+        let _ = self.timer.reset(true);
+        let _ = self.timer.set_run(parsed_run.run.clone());
```
Comment (oberien) [inline rtil/src/threads/ue/rebo/livesplit.rs:326]: unnecessary `clone`

File: rtil/src/threads/ue/rebo/livesplit.rs [hunk 3]
```diff
@@ -303,187 +341,166 @@ impl Layout {
...
+        LiveSplitLayoutColor::BehindLosingTime => &mut settings.behind_losing_time_color,
+        LiveSplitLayoutColor::NotRunning => &mut settings.not_running_color,
+        LiveSplitLayoutColor::PersonalBest => &mut settings.personal_best_color,
+        LiveSplitLayoutColor::Paused => &mut settings.paused_color,
+        LiveSplitLayoutColor::Text => &mut settings.text_color,
+    };
     let color = LiveSplitColor::rgba(color.red, color.green, color.blue, color.alpha);
-    let mut state = LIVESPLIT_STATE.lock().unwrap();
-    state.layout.general_settings_mut().text_color = color;
+    *col = color;
```
Comment (oberien) [inline rtil/src/threads/ue/rebo/livesplit.rs:445]:
```suggestion
    *col = LiveSplitColor::rgba(color.red, color.green, color.blue, color.alpha);
```

**Review by oberien — CHANGES_REQUESTED** [review]
